<a href="https://colab.research.google.com/github/apurvak3/Machine_Learning/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv('/content/boston.csv')

In [4]:
df.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [6]:
df.describe()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,252.500000,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,146.213884,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.000000,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,126.250000,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,252.500000,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,378.750000,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,505.000000,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [8]:
df.isnull().mean() * 100

Unnamed: 0    0.0
CRIM          0.0
ZN            0.0
INDUS         0.0
CHAS          0.0
NOX           0.0
RM            0.0
AGE           0.0
DIS           0.0
RAD           0.0
TAX           0.0
PTRATIO       0.0
B             0.0
LSTAT         0.0
Price         0.0
dtype: float64

In [10]:
X = df.drop('Price' , axis=1)
Y = df['Price']

In [11]:
X_train , X_test , Y_train , Y_test =train_test_split(X , Y , test_size=0.2 , random_state=0)

In [15]:
model = LinearRegression()
model.fit(X_train , Y_train)

LinearRegression()

In [16]:
y_pred=model.predict(X_test)

In [17]:
r2_model = r2_score(Y_test , y_pred)
print(r2_model)

0.5914577039362054

In [18]:
from sklearn.linear_model  import Ridge , Lasso

ridge_model = Ridge(alpha=0.1)
ridge_model.fit(X_train , Y_train)

Ridge(alpha=0.1)

In [19]:
ridge_pred_y = ridge_model.predict(X_test)
r2_model_ridge = r2_score(Y_test , ridge_pred_y)
print(r2_model_ridge)

0.5902825377430099

In [20]:
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train , Y_train)
y_pred_lasso = lasso_model.predict(X_test)
r2_model_lasso = r2_score(Y_test , y_pred_lasso)

In [21]:
print(r2_model_lasso)
print(r2_model_ridge)

0.5595863349432351
0.5902825377430099

In [25]:
lasso_model.coef_

array([-1.46527434e-03, -1.12072488e-01,  4.91904207e-02, -4.35639333e-02,
        8.63497053e-01, -0.00000000e+00,  3.61143526e+00, -1.56152499e-02,
       -1.12812413e+00,  2.17439281e-01, -1.24248521e-02, -8.89565195e-01,
        9.10857936e-03, -5.26297864e-01])

In [30]:
lower_coeff = np.where(lasso_model.coef_ > 0.5)[0]

In [31]:
print(lower_coeff)

[4 6]

In [34]:
print(list(X.columns[lower_coeff]))

['CHAS', 'RM']

In [ ]:
drop krdo and then again calculate lasso value